/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoundsRouteImport } from './routes/rounds'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as DiscsRouteImport } from './routes/discs'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoundsNewRouteImport } from './routes/rounds.new'
import { Route as RoundsIdRouteImport } from './routes/rounds.$id'
import { Route as DiscsIdRouteImport } from './routes/discs.$id'
import { Route as CoursesNewRouteImport } from './routes/courses.new'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsRoute = RoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscsRoute = DiscsRouteImport.update({
  id: '/discs',
  path: '/discs',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsNewRoute = RoundsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RoundsRoute,
} as any)
const RoundsIdRoute = RoundsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RoundsRoute,
} as any)
const DiscsIdRoute = DiscsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DiscsRoute,
} as any)
const CoursesNewRoute = CoursesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/discs': typeof DiscsRouteWithChildren
  '/records': typeof RecordsRoute
  '/rounds': typeof RoundsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/discs/$id': typeof DiscsIdRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/rounds/new': typeof RoundsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/discs': typeof DiscsRouteWithChildren
  '/records': typeof RecordsRoute
  '/rounds': typeof RoundsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/discs/$id': typeof DiscsIdRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/rounds/new': typeof RoundsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/discs': typeof DiscsRouteWithChildren
  '/records': typeof RecordsRoute
  '/rounds': typeof RoundsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/courses/$id': typeof CoursesIdRoute
  '/courses/new': typeof CoursesNewRoute
  '/discs/$id': typeof DiscsIdRoute
  '/rounds/$id': typeof RoundsIdRoute
  '/rounds/new': typeof RoundsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/discs'
    | '/records'
    | '/rounds'
    | '/settings'
    | '/stats'
    | '/courses/$id'
    | '/courses/new'
    | '/discs/$id'
    | '/rounds/$id'
    | '/rounds/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/discs'
    | '/records'
    | '/rounds'
    | '/settings'
    | '/stats'
    | '/courses/$id'
    | '/courses/new'
    | '/discs/$id'
    | '/rounds/$id'
    | '/rounds/new'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/discs'
    | '/records'
    | '/rounds'
    | '/settings'
    | '/stats'
    | '/courses/$id'
    | '/courses/new'
    | '/discs/$id'
    | '/rounds/$id'
    | '/rounds/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DiscsRoute: typeof DiscsRouteWithChildren
  RecordsRoute: typeof RecordsRoute
  RoundsRoute: typeof RoundsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds': {
      id: '/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof RoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discs': {
      id: '/discs'
      path: '/discs'
      fullPath: '/discs'
      preLoaderRoute: typeof DiscsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds/new': {
      id: '/rounds/new'
      path: '/new'
      fullPath: '/rounds/new'
      preLoaderRoute: typeof RoundsNewRouteImport
      parentRoute: typeof RoundsRoute
    }
    '/rounds/$id': {
      id: '/rounds/$id'
      path: '/$id'
      fullPath: '/rounds/$id'
      preLoaderRoute: typeof RoundsIdRouteImport
      parentRoute: typeof RoundsRoute
    }
    '/discs/$id': {
      id: '/discs/$id'
      path: '/$id'
      fullPath: '/discs/$id'
      preLoaderRoute: typeof DiscsIdRouteImport
      parentRoute: typeof DiscsRoute
    }
    '/courses/new': {
      id: '/courses/new'
      path: '/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof CoursesNewRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CoursesRouteChildren {
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesNewRoute: typeof CoursesNewRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesIdRoute: CoursesIdRoute,
  CoursesNewRoute: CoursesNewRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DiscsRouteChildren {
  DiscsIdRoute: typeof DiscsIdRoute
}

const DiscsRouteChildren: DiscsRouteChildren = {
  DiscsIdRoute: DiscsIdRoute,
}

const DiscsRouteWithChildren = DiscsRoute._addFileChildren(DiscsRouteChildren)

interface RoundsRouteChildren {
  RoundsIdRoute: typeof RoundsIdRoute
  RoundsNewRoute: typeof RoundsNewRoute
}

const RoundsRouteChildren: RoundsRouteChildren = {
  RoundsIdRoute: RoundsIdRoute,
  RoundsNewRoute: RoundsNewRoute,
}

const RoundsRouteWithChildren =
  RoundsRoute._addFileChildren(RoundsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DiscsRoute: DiscsRouteWithChildren,
  RecordsRoute: RecordsRoute,
  RoundsRoute: RoundsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
